"""Migracion inicial con roles y dashboard

Revision ID: ee3a8581978d
Revises: 
Create Date: 2025-11-10 14:16:29.620584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3a8581978d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cajero',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cajero', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cajero_email'), ['email'], unique=True)

    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('tiene_discapacidad', sa.Boolean(), nullable=False),
    sa.Column('tipo_cliente', sa.Enum('NO_AFILIADO', 'AFILIADO', name='tipocliente'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_email'), ['email'], unique=True)

    op.create_table('cdt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto_inversion', sa.Float(), nullable=False),
    sa.Column('plazo_dias', sa.Integer(), nullable=False),
    sa.Column('tasa_interes_anual', sa.Float(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_credito', sa.Enum('LIBRE_INVERSION', 'CARTERA', name='tipocredito'), nullable=False),
    sa.Column('monto_aprobado', sa.Float(), nullable=False),
    sa.Column('saldo_pendiente', sa.Float(), nullable=False),
    sa.Column('tasa_interes_anual', sa.Float(), nullable=False),
    sa.Column('plazo_meses', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuentaahorros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('exenta_4x1000', sa.Boolean(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cuenta')
    )
    op.create_table('tarjetacredito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_tarjeta', sa.String(length=16), nullable=False),
    sa.Column('cupo_total', sa.Float(), nullable=False),
    sa.Column('cupo_usado', sa.Float(), nullable=False),
    sa.Column('tasa_interes_mensual', sa.Float(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_tarjeta')
    )
    op.create_table('transaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('RETIRO', 'CONSIGNACION', 'PAGO', name='tipotransaccion'), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentaahorros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaccion')
    op.drop_table('tarjetacredito')
    op.drop_table('cuentaahorros')
    op.drop_table('credito')
    op.drop_table('cdt')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_email'))

    op.drop_table('cliente')
    with op.batch_alter_table('cajero', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cajero_email'))

    op.drop_table('cajero')
    # ### end Alembic commands ###
